[package]
name = "git-user"
version = "0.1.0"
edition = "2024"

[dependencies]
inquire = "0.6"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.5", features = ["derive"] }